var db = require('./../models/index');

var cityRepository = {

    async createCity(cityName, country, user){

        let city = await db.models.City.create({
            name: cityName,
            country: country,
            UserId: user.id
        });

        return city;
    },

    search(data, maxNum){

        let result = [];
        let i = 0;
        data = data.toLowerCase();
        Object.getOwnPropertyNames(capitals).forEach((value)=>{
            if ((!maxNum || maxNum > i) && value.toLowerCase().includes(data)){
                i++;
                result.push(value);
            }
        });

        return result;
    }
};

const capitals = {
    'Abu Dhabi': ' United Arab Emirates',
    'Abuja': ' Nigeria',
    'Accra': ' Ghana',
    'Adamstown': ' Pitcairn Islands',
    'Addis Ababa': ' Ethiopia',
    'Algiers': ' Algeria',
    'Alofi': ' Niue',
    'Amman': ' Jordan',
    'Amsterdam': ' Netherlands',
    'The Hague': 'Netherlands',
    'Andorra la Vella': ' Andorra',
    'Ankara': ' Turkey',
    'Antananarivo': ' Madagascar',
    'Apia': ' Samoa',
    'Ashgabat': ' Turkmenistan',
    'Asmara': ' Eritrea',
    'Asunción': ' Paraguay',
    'Athens': ' Greece',
    'Avarua': ' Cook Islands',
    'Baghdad': ' Iraq',
    'Baku': ' Azerbaijan',
    'Bamako': ' Mali',
    'Bandar Seri Begawan': ' Brunei',
    'Bangkok': ' Thailand',
    'Bangui': ' Central African Republic',
    'Banjul': ' Gambia',
    'Basseterre': ' Saint Kitts and Nevis',
    'Beijing': ' China',
    'Beirut': ' Lebanon',
    'Belgrade': ' Serbia',
    'Belmopan': ' Belize',
    'Berlin': ' Germany',
    'Bern': ' Switzerland',
    'Bishkek': ' Kyrgyzstan',
    'Bissau': ' Guinea-Bissau',
    'Bogotá': ' Colombia',
    'Brasília': ' Brazil',
    'Bratislava': ' Slovakia',
    'Brazzaville': ' Republic of the Congo',
    'Bridgetown': ' Barbados',
    'Brussels': ' Belgium',
    'Bucharest': ' Romania',
    'Budapest': ' Hungary',
    'Buenos Aires': ' Argentina',
    'Cairo': ' Egypt',
    'Canberra': ' Australia',
    'Caracas': ' Venezuela',
    'Castries': ' Saint Lucia',
    'Charlotte Amalie': ' United States Virgin Islands',
    'Chișinău': ' Moldova',
    'Cockburn Town': ' Turks and Caicos Islands',
    'Conakry': ' Guinea',
    'Copenhagen': ' Denmark',
    'Dakar': ' Senegal',
    'Damascus': ' Syria',
    'Dhaka': ' Bangladesh',
    'Dili': ' East Timor',
    'Djibouti': ' Djibouti',
    'Dodoma': ' Tanzania',
    'Dar es Salaam': 'Tanzania',
    'Doha': ' Qatar',
    'Douglas': ' Isle of Man',
    'Dublin': ' Ireland',
    'Dushanbe': ' Tajikistan',
    'Edinburgh of the Seven Seas': ' Tristan da Cunha',
    'El Aioun': ' Sahrawi Arab Democratic Republic [c]',
    'Tifariti': ' Sahrawi Arab Democratic Republic [c]',
    'Episkopi Cantonment': ' Akrotiri and Dhekelia',
    'Flying Fish Cove': ' Christmas Island',
    'Freetown': ' Sierra Leone',
    'Funafuti': ' Tuvalu',
    'Gaborone': ' Botswana',
    'George Town': ' Cayman Islands',
    'Georgetown': ' Ascension Island',
    'Georgetown': ' Guyana',
    'Gibraltar': ' Gibraltar',
    'Gitega': ' Burundi',
    'Guatemala City': ' Guatemala',
    'Gustavia': ' Saint Barthélemy',
    'Hagåtña': ' Guam',
    'Hamilton': ' Bermuda',
    'Hanga Roa': ' Easter Island',
    'Hanoi': ' Vietnam',
    'Harare': ' Zimbabwe',
    'Hargeisa': ' Somaliland',
    'Havana': ' Cuba',
    'Helsinki': ' Finland',
    'Honiara': ' Solomon Islands',
    'Islamabad': ' Pakistan',
    'Jakarta': ' Indonesia',
    'Jamestown': ' Saint Helena',
    'Jarabulus': ' Syrian opposition',
    'Jerusalem': ' Israel (de facto) ',
    'Jerusalem': ' Palestine (claimed)',
    'Juba': ' South Sudan',
    'Kabul': ' Afghanistan',
    'Kampala': ' Uganda',
    'Kathmandu': ' Nepal',
    'Khartoum': ' Sudan',
    'Kyiv': ' Ukraine',
    'Kigali': ' Rwanda',
    'King Edward Point': ' South Georgia and the South Sandwich Islands',
    'Kingston': ' Jamaica',
    'Kingston': ' Norfolk Island',
    'Kingstown': ' Saint Vincent and the Grenadines',
    'Kinshasa': ' Democratic Republic of the Congo',
    'Kuala Lumpur': ' Malaysia',
    'Putrajaya': 'Malaysia',
    'Kuwait City': ' Kuwait',
    'Libreville': ' Gabon',
    'Lilongwe': ' Malawi',
    'Lima': ' Peru',
    'Lisbon': ' Portugal',
    'Ljubljana': ' Slovenia',
    'Lomé': ' Togo',
    'London': ' United Kingdom',
    'Luanda': ' Angola',
    'Lusaka': ' Zambia',
    'Luxembourg': ' Luxembourg',
    'Madrid': ' Spain',
    'Majuro': ' Marshall Islands',
    'Malabo': ' Equatorial Guinea',
    'Malé': ' Maldives',
    'Managua': ' Nicaragua',
    'Manama': ' Bahrain',
    'Manila': ' Philippines',
    'Maputo': ' Mozambique',
    'Marigot': ' Saint Martin',
    'Maseru': ' Lesotho',
    'Mata-Utu': ' Wallis and Futuna',
    'Mbabane': ' Eswatini (Swaziland)',
    'Lobamba': ' Eswatini (Swaziland)',
    'Mexico City': ' Mexico',
    'Minsk': ' Belarus',
    'Mogadishu': ' Somalia',
    'Monaco': ' Monaco',
    'Monrovia': ' Liberia',
    'Montevideo': ' Uruguay',
    'Moroni': ' Comoros',
    'Moscow': ' Russia',
    'Muscat': ' Oman',
    'Nairobi': ' Kenya',
    'Nassau': ' Bahamas',
    'Naypyidaw': ' Myanmar',
    'N\'Djamena': ' Chad',
    'New Delhi': ' India',
    'Ngerulmud': ' Palau',
    'Niamey': ' Niger',
    'Nicosia': ' Cyprus',
    'Nicosia': ' Northern Cyprus',
    'Nouakchott': ' Mauritania',
    'Nouméa': ' New Caledonia',
    'Nukuʻalofa': ' Tonga',
    'Nur-Sultan': ' Kazakhstan',
    'Nuuk': ' Greenland',
    'Oranjestad': ' Aruba',
    'Oslo': ' Norway',
    'Ottawa': ' Canada',
    'Ouagadougou': ' Burkina Faso',
    'Pago Pago': ' American Samoa',
    'Palikir': ' Federated States of Micronesia',
    'Panama City': ' Panama',
    'Papeete': ' French Polynesia',
    'Paramaribo': ' Suriname',
    'Paris': ' France',
    'Philipsburg': ' Sint Maarten',
    'Phnom Penh': ' Cambodia',
    'Plymouth': ' Montserrat',
    'Brades Estate': ' Montserrat',
    'Podgorica': ' Montenegro',
    'Cetinje': ' Montenegro',
    'Port Louis': ' Mauritius',
    'Port Moresby': ' Papua New Guinea',
    'Port Vila': ' Vanuatu',
    'Port-au-Prince': ' Haiti',
    'Port of Spain': ' Trinidad and Tobago',
    'Porto-Novo': ' Benin',
    'Cotonou': ' Benin',
    'Prague': ' Czech Republic',
    'Praia': ' Cape Verde',
    'Pretoria': ' South Africa',
    'Bloemfontein': ' South Africa',
    'Cape Town': ' South Africa',
    'Pristina': ' Kosovo[g]',
    'Pyongyang': ' North Korea',
    'Quito': ' Ecuador',
    'Rabat': ' Morocco',
    'Ramallah': ' Palestine',
    'Reykjavík': ' Iceland',
    'Riga': ' Latvia',
    'Riyadh': ' Saudi Arabia',
    'Road Town': ' British Virgin Islands',
    'Rome': ' Italy',
    'Roseau': ' Dominica',
    'Saipan': ' Northern Mariana Islands',
    'San José': ' Costa Rica',
    'San Juan': ' Puerto Rico',
    'San Marino': ' San Marino',
    'San Salvador': ' El Salvador',
    'Sana\'a': ' Yemen',
    'Aden': ' Yemen',
    'Santiago': ' Chile',
    'Valparaíso': ' Chile',
    'Santo Domingo': ' Dominican Republic',
    'São Tomé': ' São Tomé and Príncipe',
    'Sarajevo': ' Bosnia and Herzegovina',
    'Seoul': ' South Korea',
    'Singapore': ' Singapore',
    'Skopje': ' North Macedonia',
    'Sofia': ' Bulgaria',
    'Sri Jayawardenepura Kotte': ' Sri Lanka',
    'Colombo': ' Sri Lanka',
    'St. George\'s': ' Grenada',
    'St. Helier': ' Jersey',
    'St. John\'s': ' Antigua and Barbuda',
    'St. Peter Port': ' Guernsey',
    'St. Pierre': ' Saint Pierre and Miquelon',
    'Stanley': ' Falkland Islands',
    'Stepanakert': ' Artsakh',
    'Stockholm': ' Sweden',
    'Sucre': ' Bolivia',
    'La Paz': ' Bolivia',
    'Sukhumi': ' Abkhazia',
    'Suva': ' Fiji',
    'Taipei': ' Taiwan',
    'Tallinn': ' Estonia',
    'Tarawa': ' Kiribati',
    'Tashkent': ' Uzbekistan',
    'Tbilisi': ' Georgia',
    'Kutaisi': ' Georgia',
    'Tegucigalpa': ' Honduras',
    'Tehran': ' Iran',
    'Thimphu': ' Bhutan',
    'Tirana': ' Albania',
    'Tiraspol': ' Transnistria',
    'Tokyo': ' Japan',
    'Tórshavn': ' Faroe Islands',
    'Tripoli': ' Libya',
    'Tskhinvali': ' South Ossetia',
    'Tunis': ' Tunisia',
    'Ulaanbaatar': ' Mongolia',
    'Vaduz': ' Liechtenstein',
    'Valletta': ' Malta',
    'The Valley': ' Anguilla',
    'Vatican City': ' Vatican City',
    'Victoria': ' Seychelles',
    'Vienna': ' Austria',
    'Vientiane': ' Laos',
    'Vilnius': ' Lithuania',
    'Warsaw': ' Poland',
    'Washington': ' United States',
    'Wellington': ' New Zealand',
    'West Island': ' Cocos (Keeling) Islands',
    'Willemstad': ' Curaçao',
    'Windhoek': ' Namibia',
    'Yamoussoukro': ' Ivory Coast',
    'Abidjan': ' Ivory Coast',
    'Yaoundé': ' Cameroon',
    'Yaren': ' Nauru',
    'Yerevan': ' Armenia',
    'Zagreb': ' Croatia'
}


module.exports = cityRepository;